---
abstract: 'provide links to CPAN module docs'
author:
  - 'David Precious <davidp@preshweb.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot-Pluggable-Module-CPANLinks
no_index:
  directory:
    - t
    - inc
requires:
  Bot::BasicBot::Pluggable: 0
  Module::Load: 0
  Test::More: 0
  URI::Title: 0
resources:
  bugtracker: https://github.com/bigpresh/Bot-BasicBot-Pluggable-Module-CPANLinks/issues
  homepage: https://github.com/bigpresh/Bot-BasicBot-Pluggable-Module-CPANLinks/
  repository: https://github.com/bigpresh/Bot-BasicBot-Pluggable-Module-CPANLinks
version: 0.01
